---
- name: 'open grafana port'
  firewalld:
    port: 3000/tcp
    permanent: true
    state: enabled
  notify: restart firewall
  become_user: root
  become: true

- name: 'open prometheus port'
  firewalld:
    port: 9090/tcp
    permanent: true
    state: enabled
  notify: restart firewall
  become_user: root
  become: true