---
- name: restart tomcat
  systemd:
    name: tomcat
    state: restarted
    daemon_reload: true

- name: restart mysql
  systemd:
    name: mariadb
    state: restarted
    daemon_reload: true

- name: restart httpd
  systemd:
    name: httpd
    state: restarted
    daemon_reload: true

- name: flush mysql privileges
  command: "/usr/bin/mysql -u root -ppassword --execute=\"FLUSH PRIVILEGES;\""

- name: restart firewall
  systemd:
    name: firewalld
    state: restarted

- name: setup ansible_local
  setup: filter=ansible_local

- name: clean yum cache
  command: yum clean all
  args:
    warn: no
